import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/utilities/Navbar";

const poppins = Poppins({ subsets: ["latin"], weight: "100" });

export const metadata = {
  title: "Anthesisme",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css"
          rel="stylesheet"
        />
      </head>
      <body className={poppins.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
